// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb/proto/OneOf.proto

package pb.example6;

public final class OneOfProto {
  private OneOfProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OneOfOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb.proto.OneOf)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 type = 1 [default = 1];</code>
     */
    boolean hasType();
    /**
     * <code>required int32 type = 1 [default = 1];</code>
     */
    int getType();

    /**
     * <code>optional .pb.proto.Student student = 2;</code>
     */
    boolean hasStudent();
    /**
     * <code>optional .pb.proto.Student student = 2;</code>
     */
    pb.example3.StudentProto.Student getStudent();
    /**
     * <code>optional .pb.proto.Student student = 2;</code>
     */
    pb.example3.StudentProto.StudentOrBuilder getStudentOrBuilder();

    /**
     * <code>optional .pb.proto.Teacher teacher = 3;</code>
     */
    boolean hasTeacher();
    /**
     * <code>optional .pb.proto.Teacher teacher = 3;</code>
     */
    pb.example3.TeacherProto.Teacher getTeacher();
    /**
     * <code>optional .pb.proto.Teacher teacher = 3;</code>
     */
    pb.example3.TeacherProto.TeacherOrBuilder getTeacherOrBuilder();

    public pb.example6.OneOfProto.OneOf.DataCase getDataCase();
  }
  /**
   * Protobuf type {@code pb.proto.OneOf}
   */
  public  static final class OneOf extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pb.proto.OneOf)
      OneOfOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OneOf.newBuilder() to construct.
    private OneOf(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OneOf() {
      type_ = 1;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OneOf(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              type_ = input.readInt32();
              break;
            }
            case 18: {
              pb.example3.StudentProto.Student.Builder subBuilder = null;
              if (dataCase_ == 2) {
                subBuilder = ((pb.example3.StudentProto.Student) data_).toBuilder();
              }
              data_ =
                  input.readMessage(pb.example3.StudentProto.Student.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((pb.example3.StudentProto.Student) data_);
                data_ = subBuilder.buildPartial();
              }
              dataCase_ = 2;
              break;
            }
            case 26: {
              pb.example3.TeacherProto.Teacher.Builder subBuilder = null;
              if (dataCase_ == 3) {
                subBuilder = ((pb.example3.TeacherProto.Teacher) data_).toBuilder();
              }
              data_ =
                  input.readMessage(pb.example3.TeacherProto.Teacher.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((pb.example3.TeacherProto.Teacher) data_);
                data_ = subBuilder.buildPartial();
              }
              dataCase_ = 3;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pb.example6.OneOfProto.internal_static_pb_proto_OneOf_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pb.example6.OneOfProto.internal_static_pb_proto_OneOf_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pb.example6.OneOfProto.OneOf.class, pb.example6.OneOfProto.OneOf.Builder.class);
    }

    private int bitField0_;
    private int dataCase_ = 0;
    private java.lang.Object data_;
    public enum DataCase
        implements com.google.protobuf.Internal.EnumLite {
      STUDENT(2),
      TEACHER(3),
      DATA_NOT_SET(0);
      private final int value;
      private DataCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataCase valueOf(int value) {
        return forNumber(value);
      }

      public static DataCase forNumber(int value) {
        switch (value) {
          case 2: return STUDENT;
          case 3: return TEACHER;
          case 0: return DATA_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public DataCase
    getDataCase() {
      return DataCase.forNumber(
          dataCase_);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>required int32 type = 1 [default = 1];</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 type = 1 [default = 1];</code>
     */
    public int getType() {
      return type_;
    }

    public static final int STUDENT_FIELD_NUMBER = 2;
    /**
     * <code>optional .pb.proto.Student student = 2;</code>
     */
    public boolean hasStudent() {
      return dataCase_ == 2;
    }
    /**
     * <code>optional .pb.proto.Student student = 2;</code>
     */
    public pb.example3.StudentProto.Student getStudent() {
      if (dataCase_ == 2) {
         return (pb.example3.StudentProto.Student) data_;
      }
      return pb.example3.StudentProto.Student.getDefaultInstance();
    }
    /**
     * <code>optional .pb.proto.Student student = 2;</code>
     */
    public pb.example3.StudentProto.StudentOrBuilder getStudentOrBuilder() {
      if (dataCase_ == 2) {
         return (pb.example3.StudentProto.Student) data_;
      }
      return pb.example3.StudentProto.Student.getDefaultInstance();
    }

    public static final int TEACHER_FIELD_NUMBER = 3;
    /**
     * <code>optional .pb.proto.Teacher teacher = 3;</code>
     */
    public boolean hasTeacher() {
      return dataCase_ == 3;
    }
    /**
     * <code>optional .pb.proto.Teacher teacher = 3;</code>
     */
    public pb.example3.TeacherProto.Teacher getTeacher() {
      if (dataCase_ == 3) {
         return (pb.example3.TeacherProto.Teacher) data_;
      }
      return pb.example3.TeacherProto.Teacher.getDefaultInstance();
    }
    /**
     * <code>optional .pb.proto.Teacher teacher = 3;</code>
     */
    public pb.example3.TeacherProto.TeacherOrBuilder getTeacherOrBuilder() {
      if (dataCase_ == 3) {
         return (pb.example3.TeacherProto.Teacher) data_;
      }
      return pb.example3.TeacherProto.Teacher.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, type_);
      }
      if (dataCase_ == 2) {
        output.writeMessage(2, (pb.example3.StudentProto.Student) data_);
      }
      if (dataCase_ == 3) {
        output.writeMessage(3, (pb.example3.TeacherProto.Teacher) data_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, type_);
      }
      if (dataCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (pb.example3.StudentProto.Student) data_);
      }
      if (dataCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (pb.example3.TeacherProto.Teacher) data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pb.example6.OneOfProto.OneOf)) {
        return super.equals(obj);
      }
      pb.example6.OneOfProto.OneOf other = (pb.example6.OneOfProto.OneOf) obj;

      boolean result = true;
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && (getType()
            == other.getType());
      }
      result = result && getDataCase().equals(
          other.getDataCase());
      if (!result) return false;
      switch (dataCase_) {
        case 2:
          result = result && getStudent()
              .equals(other.getStudent());
          break;
        case 3:
          result = result && getTeacher()
              .equals(other.getTeacher());
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType();
      }
      switch (dataCase_) {
        case 2:
          hash = (37 * hash) + STUDENT_FIELD_NUMBER;
          hash = (53 * hash) + getStudent().hashCode();
          break;
        case 3:
          hash = (37 * hash) + TEACHER_FIELD_NUMBER;
          hash = (53 * hash) + getTeacher().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pb.example6.OneOfProto.OneOf parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.example6.OneOfProto.OneOf parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.example6.OneOfProto.OneOf parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.example6.OneOfProto.OneOf parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.example6.OneOfProto.OneOf parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.example6.OneOfProto.OneOf parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.example6.OneOfProto.OneOf parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pb.example6.OneOfProto.OneOf parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pb.example6.OneOfProto.OneOf parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pb.example6.OneOfProto.OneOf parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pb.example6.OneOfProto.OneOf parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pb.example6.OneOfProto.OneOf parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pb.example6.OneOfProto.OneOf prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pb.proto.OneOf}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb.proto.OneOf)
        pb.example6.OneOfProto.OneOfOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pb.example6.OneOfProto.internal_static_pb_proto_OneOf_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pb.example6.OneOfProto.internal_static_pb_proto_OneOf_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pb.example6.OneOfProto.OneOf.class, pb.example6.OneOfProto.OneOf.Builder.class);
      }

      // Construct using pb.example6.OneOfProto.OneOf.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        dataCase_ = 0;
        data_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pb.example6.OneOfProto.internal_static_pb_proto_OneOf_descriptor;
      }

      @java.lang.Override
      public pb.example6.OneOfProto.OneOf getDefaultInstanceForType() {
        return pb.example6.OneOfProto.OneOf.getDefaultInstance();
      }

      @java.lang.Override
      public pb.example6.OneOfProto.OneOf build() {
        pb.example6.OneOfProto.OneOf result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pb.example6.OneOfProto.OneOf buildPartial() {
        pb.example6.OneOfProto.OneOf result = new pb.example6.OneOfProto.OneOf(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (dataCase_ == 2) {
          if (studentBuilder_ == null) {
            result.data_ = data_;
          } else {
            result.data_ = studentBuilder_.build();
          }
        }
        if (dataCase_ == 3) {
          if (teacherBuilder_ == null) {
            result.data_ = data_;
          } else {
            result.data_ = teacherBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.dataCase_ = dataCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pb.example6.OneOfProto.OneOf) {
          return mergeFrom((pb.example6.OneOfProto.OneOf)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pb.example6.OneOfProto.OneOf other) {
        if (other == pb.example6.OneOfProto.OneOf.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        switch (other.getDataCase()) {
          case STUDENT: {
            mergeStudent(other.getStudent());
            break;
          }
          case TEACHER: {
            mergeTeacher(other.getTeacher());
            break;
          }
          case DATA_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasType()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pb.example6.OneOfProto.OneOf parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pb.example6.OneOfProto.OneOf) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int dataCase_ = 0;
      private java.lang.Object data_;
      public DataCase
          getDataCase() {
        return DataCase.forNumber(
            dataCase_);
      }

      public Builder clearData() {
        dataCase_ = 0;
        data_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private int type_ = 1;
      /**
       * <code>required int32 type = 1 [default = 1];</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 type = 1 [default = 1];</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>required int32 type = 1 [default = 1];</code>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 type = 1 [default = 1];</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 1;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          pb.example3.StudentProto.Student, pb.example3.StudentProto.Student.Builder, pb.example3.StudentProto.StudentOrBuilder> studentBuilder_;
      /**
       * <code>optional .pb.proto.Student student = 2;</code>
       */
      public boolean hasStudent() {
        return dataCase_ == 2;
      }
      /**
       * <code>optional .pb.proto.Student student = 2;</code>
       */
      public pb.example3.StudentProto.Student getStudent() {
        if (studentBuilder_ == null) {
          if (dataCase_ == 2) {
            return (pb.example3.StudentProto.Student) data_;
          }
          return pb.example3.StudentProto.Student.getDefaultInstance();
        } else {
          if (dataCase_ == 2) {
            return studentBuilder_.getMessage();
          }
          return pb.example3.StudentProto.Student.getDefaultInstance();
        }
      }
      /**
       * <code>optional .pb.proto.Student student = 2;</code>
       */
      public Builder setStudent(pb.example3.StudentProto.Student value) {
        if (studentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
          onChanged();
        } else {
          studentBuilder_.setMessage(value);
        }
        dataCase_ = 2;
        return this;
      }
      /**
       * <code>optional .pb.proto.Student student = 2;</code>
       */
      public Builder setStudent(
          pb.example3.StudentProto.Student.Builder builderForValue) {
        if (studentBuilder_ == null) {
          data_ = builderForValue.build();
          onChanged();
        } else {
          studentBuilder_.setMessage(builderForValue.build());
        }
        dataCase_ = 2;
        return this;
      }
      /**
       * <code>optional .pb.proto.Student student = 2;</code>
       */
      public Builder mergeStudent(pb.example3.StudentProto.Student value) {
        if (studentBuilder_ == null) {
          if (dataCase_ == 2 &&
              data_ != pb.example3.StudentProto.Student.getDefaultInstance()) {
            data_ = pb.example3.StudentProto.Student.newBuilder((pb.example3.StudentProto.Student) data_)
                .mergeFrom(value).buildPartial();
          } else {
            data_ = value;
          }
          onChanged();
        } else {
          if (dataCase_ == 2) {
            studentBuilder_.mergeFrom(value);
          }
          studentBuilder_.setMessage(value);
        }
        dataCase_ = 2;
        return this;
      }
      /**
       * <code>optional .pb.proto.Student student = 2;</code>
       */
      public Builder clearStudent() {
        if (studentBuilder_ == null) {
          if (dataCase_ == 2) {
            dataCase_ = 0;
            data_ = null;
            onChanged();
          }
        } else {
          if (dataCase_ == 2) {
            dataCase_ = 0;
            data_ = null;
          }
          studentBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .pb.proto.Student student = 2;</code>
       */
      public pb.example3.StudentProto.Student.Builder getStudentBuilder() {
        return getStudentFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .pb.proto.Student student = 2;</code>
       */
      public pb.example3.StudentProto.StudentOrBuilder getStudentOrBuilder() {
        if ((dataCase_ == 2) && (studentBuilder_ != null)) {
          return studentBuilder_.getMessageOrBuilder();
        } else {
          if (dataCase_ == 2) {
            return (pb.example3.StudentProto.Student) data_;
          }
          return pb.example3.StudentProto.Student.getDefaultInstance();
        }
      }
      /**
       * <code>optional .pb.proto.Student student = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          pb.example3.StudentProto.Student, pb.example3.StudentProto.Student.Builder, pb.example3.StudentProto.StudentOrBuilder> 
          getStudentFieldBuilder() {
        if (studentBuilder_ == null) {
          if (!(dataCase_ == 2)) {
            data_ = pb.example3.StudentProto.Student.getDefaultInstance();
          }
          studentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              pb.example3.StudentProto.Student, pb.example3.StudentProto.Student.Builder, pb.example3.StudentProto.StudentOrBuilder>(
                  (pb.example3.StudentProto.Student) data_,
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        dataCase_ = 2;
        onChanged();;
        return studentBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          pb.example3.TeacherProto.Teacher, pb.example3.TeacherProto.Teacher.Builder, pb.example3.TeacherProto.TeacherOrBuilder> teacherBuilder_;
      /**
       * <code>optional .pb.proto.Teacher teacher = 3;</code>
       */
      public boolean hasTeacher() {
        return dataCase_ == 3;
      }
      /**
       * <code>optional .pb.proto.Teacher teacher = 3;</code>
       */
      public pb.example3.TeacherProto.Teacher getTeacher() {
        if (teacherBuilder_ == null) {
          if (dataCase_ == 3) {
            return (pb.example3.TeacherProto.Teacher) data_;
          }
          return pb.example3.TeacherProto.Teacher.getDefaultInstance();
        } else {
          if (dataCase_ == 3) {
            return teacherBuilder_.getMessage();
          }
          return pb.example3.TeacherProto.Teacher.getDefaultInstance();
        }
      }
      /**
       * <code>optional .pb.proto.Teacher teacher = 3;</code>
       */
      public Builder setTeacher(pb.example3.TeacherProto.Teacher value) {
        if (teacherBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
          onChanged();
        } else {
          teacherBuilder_.setMessage(value);
        }
        dataCase_ = 3;
        return this;
      }
      /**
       * <code>optional .pb.proto.Teacher teacher = 3;</code>
       */
      public Builder setTeacher(
          pb.example3.TeacherProto.Teacher.Builder builderForValue) {
        if (teacherBuilder_ == null) {
          data_ = builderForValue.build();
          onChanged();
        } else {
          teacherBuilder_.setMessage(builderForValue.build());
        }
        dataCase_ = 3;
        return this;
      }
      /**
       * <code>optional .pb.proto.Teacher teacher = 3;</code>
       */
      public Builder mergeTeacher(pb.example3.TeacherProto.Teacher value) {
        if (teacherBuilder_ == null) {
          if (dataCase_ == 3 &&
              data_ != pb.example3.TeacherProto.Teacher.getDefaultInstance()) {
            data_ = pb.example3.TeacherProto.Teacher.newBuilder((pb.example3.TeacherProto.Teacher) data_)
                .mergeFrom(value).buildPartial();
          } else {
            data_ = value;
          }
          onChanged();
        } else {
          if (dataCase_ == 3) {
            teacherBuilder_.mergeFrom(value);
          }
          teacherBuilder_.setMessage(value);
        }
        dataCase_ = 3;
        return this;
      }
      /**
       * <code>optional .pb.proto.Teacher teacher = 3;</code>
       */
      public Builder clearTeacher() {
        if (teacherBuilder_ == null) {
          if (dataCase_ == 3) {
            dataCase_ = 0;
            data_ = null;
            onChanged();
          }
        } else {
          if (dataCase_ == 3) {
            dataCase_ = 0;
            data_ = null;
          }
          teacherBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .pb.proto.Teacher teacher = 3;</code>
       */
      public pb.example3.TeacherProto.Teacher.Builder getTeacherBuilder() {
        return getTeacherFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .pb.proto.Teacher teacher = 3;</code>
       */
      public pb.example3.TeacherProto.TeacherOrBuilder getTeacherOrBuilder() {
        if ((dataCase_ == 3) && (teacherBuilder_ != null)) {
          return teacherBuilder_.getMessageOrBuilder();
        } else {
          if (dataCase_ == 3) {
            return (pb.example3.TeacherProto.Teacher) data_;
          }
          return pb.example3.TeacherProto.Teacher.getDefaultInstance();
        }
      }
      /**
       * <code>optional .pb.proto.Teacher teacher = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          pb.example3.TeacherProto.Teacher, pb.example3.TeacherProto.Teacher.Builder, pb.example3.TeacherProto.TeacherOrBuilder> 
          getTeacherFieldBuilder() {
        if (teacherBuilder_ == null) {
          if (!(dataCase_ == 3)) {
            data_ = pb.example3.TeacherProto.Teacher.getDefaultInstance();
          }
          teacherBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              pb.example3.TeacherProto.Teacher, pb.example3.TeacherProto.Teacher.Builder, pb.example3.TeacherProto.TeacherOrBuilder>(
                  (pb.example3.TeacherProto.Teacher) data_,
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        dataCase_ = 3;
        onChanged();;
        return teacherBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pb.proto.OneOf)
    }

    // @@protoc_insertion_point(class_scope:pb.proto.OneOf)
    private static final pb.example6.OneOfProto.OneOf DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pb.example6.OneOfProto.OneOf();
    }

    public static pb.example6.OneOfProto.OneOf getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<OneOf>
        PARSER = new com.google.protobuf.AbstractParser<OneOf>() {
      @java.lang.Override
      public OneOf parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OneOf(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OneOf> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OneOf> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pb.example6.OneOfProto.OneOf getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_proto_OneOf_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_proto_OneOf_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024pb/proto/OneOf.proto\022\010pb.proto\032\026pb/pro" +
      "to/Student.proto\032\026pb/proto/Teacher.proto" +
      "\"l\n\005OneOf\022\017\n\004type\030\001 \002(\005:\0011\022$\n\007student\030\002 " +
      "\001(\0132\021.pb.proto.StudentH\000\022$\n\007teacher\030\003 \001(" +
      "\0132\021.pb.proto.TeacherH\000B\006\n\004dataB\031\n\013pb.exa" +
      "mple6B\nOneOfProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          pb.example3.StudentProto.getDescriptor(),
          pb.example3.TeacherProto.getDescriptor(),
        }, assigner);
    internal_static_pb_proto_OneOf_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pb_proto_OneOf_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_proto_OneOf_descriptor,
        new java.lang.String[] { "Type", "Student", "Teacher", "Data", });
    pb.example3.StudentProto.getDescriptor();
    pb.example3.TeacherProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
