// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb/proto/SearchResponse.proto

package pb.example4;

public final class SearchResponseProto {
  private SearchResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SearchResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb.example4.SearchResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .pb.example4.SearchResponse.Result result = 1;</code>
     */
    boolean hasResult();
    /**
     * <code>optional .pb.example4.SearchResponse.Result result = 1;</code>
     */
    pb.example4.SearchResponseProto.SearchResponse.Result getResult();
    /**
     * <code>optional .pb.example4.SearchResponse.Result result = 1;</code>
     */
    pb.example4.SearchResponseProto.SearchResponse.ResultOrBuilder getResultOrBuilder();
  }
  /**
   * Protobuf type {@code pb.example4.SearchResponse}
   */
  public  static final class SearchResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pb.example4.SearchResponse)
      SearchResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SearchResponse.newBuilder() to construct.
    private SearchResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SearchResponse() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SearchResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              pb.example4.SearchResponseProto.SearchResponse.Result.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = result_.toBuilder();
              }
              result_ = input.readMessage(pb.example4.SearchResponseProto.SearchResponse.Result.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(result_);
                result_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pb.example4.SearchResponseProto.internal_static_pb_example4_SearchResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pb.example4.SearchResponseProto.internal_static_pb_example4_SearchResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pb.example4.SearchResponseProto.SearchResponse.class, pb.example4.SearchResponseProto.SearchResponse.Builder.class);
    }

    public interface ResultOrBuilder extends
        // @@protoc_insertion_point(interface_extends:pb.example4.SearchResponse.Result)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required int32 count = 1;</code>
       */
      boolean hasCount();
      /**
       * <code>required int32 count = 1;</code>
       */
      int getCount();

      /**
       * <code>repeated .pb.example4.SearchResponse.Result.Order orders = 2;</code>
       */
      java.util.List<pb.example4.SearchResponseProto.SearchResponse.Result.Order> 
          getOrdersList();
      /**
       * <code>repeated .pb.example4.SearchResponse.Result.Order orders = 2;</code>
       */
      pb.example4.SearchResponseProto.SearchResponse.Result.Order getOrders(int index);
      /**
       * <code>repeated .pb.example4.SearchResponse.Result.Order orders = 2;</code>
       */
      int getOrdersCount();
      /**
       * <code>repeated .pb.example4.SearchResponse.Result.Order orders = 2;</code>
       */
      java.util.List<? extends pb.example4.SearchResponseProto.SearchResponse.Result.OrderOrBuilder> 
          getOrdersOrBuilderList();
      /**
       * <code>repeated .pb.example4.SearchResponse.Result.Order orders = 2;</code>
       */
      pb.example4.SearchResponseProto.SearchResponse.Result.OrderOrBuilder getOrdersOrBuilder(
          int index);
    }
    /**
     * Protobuf type {@code pb.example4.SearchResponse.Result}
     */
    public  static final class Result extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:pb.example4.SearchResponse.Result)
        ResultOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Result.newBuilder() to construct.
      private Result(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Result() {
        count_ = 0;
        orders_ = java.util.Collections.emptyList();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Result(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                bitField0_ |= 0x00000001;
                count_ = input.readInt32();
                break;
              }
              case 18: {
                if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                  orders_ = new java.util.ArrayList<pb.example4.SearchResponseProto.SearchResponse.Result.Order>();
                  mutable_bitField0_ |= 0x00000002;
                }
                orders_.add(
                    input.readMessage(pb.example4.SearchResponseProto.SearchResponse.Result.Order.PARSER, extensionRegistry));
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
            orders_ = java.util.Collections.unmodifiableList(orders_);
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pb.example4.SearchResponseProto.internal_static_pb_example4_SearchResponse_Result_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pb.example4.SearchResponseProto.internal_static_pb_example4_SearchResponse_Result_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pb.example4.SearchResponseProto.SearchResponse.Result.class, pb.example4.SearchResponseProto.SearchResponse.Result.Builder.class);
      }

      public interface OrderOrBuilder extends
          // @@protoc_insertion_point(interface_extends:pb.example4.SearchResponse.Result.Order)
          com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional string order_num = 1;</code>
         */
        boolean hasOrderNum();
        /**
         * <code>optional string order_num = 1;</code>
         */
        java.lang.String getOrderNum();
        /**
         * <code>optional string order_num = 1;</code>
         */
        com.google.protobuf.ByteString
            getOrderNumBytes();

        /**
         * <code>optional string address = 2;</code>
         */
        boolean hasAddress();
        /**
         * <code>optional string address = 2;</code>
         */
        java.lang.String getAddress();
        /**
         * <code>optional string address = 2;</code>
         */
        com.google.protobuf.ByteString
            getAddressBytes();
      }
      /**
       * Protobuf type {@code pb.example4.SearchResponse.Result.Order}
       */
      public  static final class Order extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:pb.example4.SearchResponse.Result.Order)
          OrderOrBuilder {
      private static final long serialVersionUID = 0L;
        // Use Order.newBuilder() to construct.
        private Order(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
          super(builder);
        }
        private Order() {
          orderNum_ = "";
          address_ = "";
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
          return this.unknownFields;
        }
        private Order(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          this();
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          int mutable_bitField0_ = 0;
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 10: {
                  com.google.protobuf.ByteString bs = input.readBytes();
                  bitField0_ |= 0x00000001;
                  orderNum_ = bs;
                  break;
                }
                case 18: {
                  com.google.protobuf.ByteString bs = input.readBytes();
                  bitField0_ |= 0x00000002;
                  address_ = bs;
                  break;
                }
                default: {
                  if (!parseUnknownField(
                      input, unknownFields, extensionRegistry, tag)) {
                    done = true;
                  }
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
          } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
          }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return pb.example4.SearchResponseProto.internal_static_pb_example4_SearchResponse_Result_Order_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return pb.example4.SearchResponseProto.internal_static_pb_example4_SearchResponse_Result_Order_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  pb.example4.SearchResponseProto.SearchResponse.Result.Order.class, pb.example4.SearchResponseProto.SearchResponse.Result.Order.Builder.class);
        }

        private int bitField0_;
        public static final int ORDER_NUM_FIELD_NUMBER = 1;
        private volatile java.lang.Object orderNum_;
        /**
         * <code>optional string order_num = 1;</code>
         */
        public boolean hasOrderNum() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional string order_num = 1;</code>
         */
        public java.lang.String getOrderNum() {
          java.lang.Object ref = orderNum_;
          if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
          } else {
            com.google.protobuf.ByteString bs = 
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              orderNum_ = s;
            }
            return s;
          }
        }
        /**
         * <code>optional string order_num = 1;</code>
         */
        public com.google.protobuf.ByteString
            getOrderNumBytes() {
          java.lang.Object ref = orderNum_;
          if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            orderNum_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }

        public static final int ADDRESS_FIELD_NUMBER = 2;
        private volatile java.lang.Object address_;
        /**
         * <code>optional string address = 2;</code>
         */
        public boolean hasAddress() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string address = 2;</code>
         */
        public java.lang.String getAddress() {
          java.lang.Object ref = address_;
          if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
          } else {
            com.google.protobuf.ByteString bs = 
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              address_ = s;
            }
            return s;
          }
        }
        /**
         * <code>optional string address = 2;</code>
         */
        public com.google.protobuf.ByteString
            getAddressBytes() {
          java.lang.Object ref = address_;
          if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            address_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }

        private byte memoizedIsInitialized = -1;
        @java.lang.Override
        public final boolean isInitialized() {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return true;
          if (isInitialized == 0) return false;

          memoizedIsInitialized = 1;
          return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                            throws java.io.IOException {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, orderNum_);
          }
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, address_);
          }
          unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
          int size = memoizedSize;
          if (size != -1) return size;

          size = 0;
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, orderNum_);
          }
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, address_);
          }
          size += unknownFields.getSerializedSize();
          memoizedSize = size;
          return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
          if (obj == this) {
           return true;
          }
          if (!(obj instanceof pb.example4.SearchResponseProto.SearchResponse.Result.Order)) {
            return super.equals(obj);
          }
          pb.example4.SearchResponseProto.SearchResponse.Result.Order other = (pb.example4.SearchResponseProto.SearchResponse.Result.Order) obj;

          boolean result = true;
          result = result && (hasOrderNum() == other.hasOrderNum());
          if (hasOrderNum()) {
            result = result && getOrderNum()
                .equals(other.getOrderNum());
          }
          result = result && (hasAddress() == other.hasAddress());
          if (hasAddress()) {
            result = result && getAddress()
                .equals(other.getAddress());
          }
          result = result && unknownFields.equals(other.unknownFields);
          return result;
        }

        @java.lang.Override
        public int hashCode() {
          if (memoizedHashCode != 0) {
            return memoizedHashCode;
          }
          int hash = 41;
          hash = (19 * hash) + getDescriptor().hashCode();
          if (hasOrderNum()) {
            hash = (37 * hash) + ORDER_NUM_FIELD_NUMBER;
            hash = (53 * hash) + getOrderNum().hashCode();
          }
          if (hasAddress()) {
            hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
            hash = (53 * hash) + getAddress().hashCode();
          }
          hash = (29 * hash) + unknownFields.hashCode();
          memoizedHashCode = hash;
          return hash;
        }

        public static pb.example4.SearchResponseProto.SearchResponse.Result.Order parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data);
        }
        public static pb.example4.SearchResponseProto.SearchResponse.Result.Order parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data, extensionRegistry);
        }
        public static pb.example4.SearchResponseProto.SearchResponse.Result.Order parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data);
        }
        public static pb.example4.SearchResponseProto.SearchResponse.Result.Order parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data, extensionRegistry);
        }
        public static pb.example4.SearchResponseProto.SearchResponse.Result.Order parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data);
        }
        public static pb.example4.SearchResponseProto.SearchResponse.Result.Order parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data, extensionRegistry);
        }
        public static pb.example4.SearchResponseProto.SearchResponse.Result.Order parseFrom(java.io.InputStream input)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
        }
        public static pb.example4.SearchResponseProto.SearchResponse.Result.Order parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static pb.example4.SearchResponseProto.SearchResponse.Result.Order parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
        }
        public static pb.example4.SearchResponseProto.SearchResponse.Result.Order parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static pb.example4.SearchResponseProto.SearchResponse.Result.Order parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
        }
        public static pb.example4.SearchResponseProto.SearchResponse.Result.Order parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
          return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(pb.example4.SearchResponseProto.SearchResponse.Result.Order prototype) {
          return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @java.lang.Override
        public Builder toBuilder() {
          return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          Builder builder = new Builder(parent);
          return builder;
        }
        /**
         * Protobuf type {@code pb.example4.SearchResponse.Result.Order}
         */
        public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:pb.example4.SearchResponse.Result.Order)
            pb.example4.SearchResponseProto.SearchResponse.Result.OrderOrBuilder {
          public static final com.google.protobuf.Descriptors.Descriptor
              getDescriptor() {
            return pb.example4.SearchResponseProto.internal_static_pb_example4_SearchResponse_Result_Order_descriptor;
          }

          @java.lang.Override
          protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
              internalGetFieldAccessorTable() {
            return pb.example4.SearchResponseProto.internal_static_pb_example4_SearchResponse_Result_Order_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                    pb.example4.SearchResponseProto.SearchResponse.Result.Order.class, pb.example4.SearchResponseProto.SearchResponse.Result.Order.Builder.class);
          }

          // Construct using pb.example4.SearchResponseProto.SearchResponse.Result.Order.newBuilder()
          private Builder() {
            maybeForceBuilderInitialization();
          }

          private Builder(
              com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
          }
          private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
          }
          @java.lang.Override
          public Builder clear() {
            super.clear();
            orderNum_ = "";
            bitField0_ = (bitField0_ & ~0x00000001);
            address_ = "";
            bitField0_ = (bitField0_ & ~0x00000002);
            return this;
          }

          @java.lang.Override
          public com.google.protobuf.Descriptors.Descriptor
              getDescriptorForType() {
            return pb.example4.SearchResponseProto.internal_static_pb_example4_SearchResponse_Result_Order_descriptor;
          }

          @java.lang.Override
          public pb.example4.SearchResponseProto.SearchResponse.Result.Order getDefaultInstanceForType() {
            return pb.example4.SearchResponseProto.SearchResponse.Result.Order.getDefaultInstance();
          }

          @java.lang.Override
          public pb.example4.SearchResponseProto.SearchResponse.Result.Order build() {
            pb.example4.SearchResponseProto.SearchResponse.Result.Order result = buildPartial();
            if (!result.isInitialized()) {
              throw newUninitializedMessageException(result);
            }
            return result;
          }

          @java.lang.Override
          public pb.example4.SearchResponseProto.SearchResponse.Result.Order buildPartial() {
            pb.example4.SearchResponseProto.SearchResponse.Result.Order result = new pb.example4.SearchResponseProto.SearchResponse.Result.Order(this);
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
              to_bitField0_ |= 0x00000001;
            }
            result.orderNum_ = orderNum_;
            if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
              to_bitField0_ |= 0x00000002;
            }
            result.address_ = address_;
            result.bitField0_ = to_bitField0_;
            onBuilt();
            return result;
          }

          @java.lang.Override
          public Builder clone() {
            return (Builder) super.clone();
          }
          @java.lang.Override
          public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
            return (Builder) super.setField(field, value);
          }
          @java.lang.Override
          public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
            return (Builder) super.clearField(field);
          }
          @java.lang.Override
          public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return (Builder) super.clearOneof(oneof);
          }
          @java.lang.Override
          public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, java.lang.Object value) {
            return (Builder) super.setRepeatedField(field, index, value);
          }
          @java.lang.Override
          public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
            return (Builder) super.addRepeatedField(field, value);
          }
          @java.lang.Override
          public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof pb.example4.SearchResponseProto.SearchResponse.Result.Order) {
              return mergeFrom((pb.example4.SearchResponseProto.SearchResponse.Result.Order)other);
            } else {
              super.mergeFrom(other);
              return this;
            }
          }

          public Builder mergeFrom(pb.example4.SearchResponseProto.SearchResponse.Result.Order other) {
            if (other == pb.example4.SearchResponseProto.SearchResponse.Result.Order.getDefaultInstance()) return this;
            if (other.hasOrderNum()) {
              bitField0_ |= 0x00000001;
              orderNum_ = other.orderNum_;
              onChanged();
            }
            if (other.hasAddress()) {
              bitField0_ |= 0x00000002;
              address_ = other.address_;
              onChanged();
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
          }

          @java.lang.Override
          public final boolean isInitialized() {
            return true;
          }

          @java.lang.Override
          public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
            pb.example4.SearchResponseProto.SearchResponse.Result.Order parsedMessage = null;
            try {
              parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
              parsedMessage = (pb.example4.SearchResponseProto.SearchResponse.Result.Order) e.getUnfinishedMessage();
              throw e.unwrapIOException();
            } finally {
              if (parsedMessage != null) {
                mergeFrom(parsedMessage);
              }
            }
            return this;
          }
          private int bitField0_;

          private java.lang.Object orderNum_ = "";
          /**
           * <code>optional string order_num = 1;</code>
           */
          public boolean hasOrderNum() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
          }
          /**
           * <code>optional string order_num = 1;</code>
           */
          public java.lang.String getOrderNum() {
            java.lang.Object ref = orderNum_;
            if (!(ref instanceof java.lang.String)) {
              com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
              java.lang.String s = bs.toStringUtf8();
              if (bs.isValidUtf8()) {
                orderNum_ = s;
              }
              return s;
            } else {
              return (java.lang.String) ref;
            }
          }
          /**
           * <code>optional string order_num = 1;</code>
           */
          public com.google.protobuf.ByteString
              getOrderNumBytes() {
            java.lang.Object ref = orderNum_;
            if (ref instanceof String) {
              com.google.protobuf.ByteString b = 
                  com.google.protobuf.ByteString.copyFromUtf8(
                      (java.lang.String) ref);
              orderNum_ = b;
              return b;
            } else {
              return (com.google.protobuf.ByteString) ref;
            }
          }
          /**
           * <code>optional string order_num = 1;</code>
           */
          public Builder setOrderNum(
              java.lang.String value) {
            if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
            orderNum_ = value;
            onChanged();
            return this;
          }
          /**
           * <code>optional string order_num = 1;</code>
           */
          public Builder clearOrderNum() {
            bitField0_ = (bitField0_ & ~0x00000001);
            orderNum_ = getDefaultInstance().getOrderNum();
            onChanged();
            return this;
          }
          /**
           * <code>optional string order_num = 1;</code>
           */
          public Builder setOrderNumBytes(
              com.google.protobuf.ByteString value) {
            if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
            orderNum_ = value;
            onChanged();
            return this;
          }

          private java.lang.Object address_ = "";
          /**
           * <code>optional string address = 2;</code>
           */
          public boolean hasAddress() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
          }
          /**
           * <code>optional string address = 2;</code>
           */
          public java.lang.String getAddress() {
            java.lang.Object ref = address_;
            if (!(ref instanceof java.lang.String)) {
              com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
              java.lang.String s = bs.toStringUtf8();
              if (bs.isValidUtf8()) {
                address_ = s;
              }
              return s;
            } else {
              return (java.lang.String) ref;
            }
          }
          /**
           * <code>optional string address = 2;</code>
           */
          public com.google.protobuf.ByteString
              getAddressBytes() {
            java.lang.Object ref = address_;
            if (ref instanceof String) {
              com.google.protobuf.ByteString b = 
                  com.google.protobuf.ByteString.copyFromUtf8(
                      (java.lang.String) ref);
              address_ = b;
              return b;
            } else {
              return (com.google.protobuf.ByteString) ref;
            }
          }
          /**
           * <code>optional string address = 2;</code>
           */
          public Builder setAddress(
              java.lang.String value) {
            if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
            address_ = value;
            onChanged();
            return this;
          }
          /**
           * <code>optional string address = 2;</code>
           */
          public Builder clearAddress() {
            bitField0_ = (bitField0_ & ~0x00000002);
            address_ = getDefaultInstance().getAddress();
            onChanged();
            return this;
          }
          /**
           * <code>optional string address = 2;</code>
           */
          public Builder setAddressBytes(
              com.google.protobuf.ByteString value) {
            if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
            address_ = value;
            onChanged();
            return this;
          }
          @java.lang.Override
          public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
          }

          @java.lang.Override
          public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
          }


          // @@protoc_insertion_point(builder_scope:pb.example4.SearchResponse.Result.Order)
        }

        // @@protoc_insertion_point(class_scope:pb.example4.SearchResponse.Result.Order)
        private static final pb.example4.SearchResponseProto.SearchResponse.Result.Order DEFAULT_INSTANCE;
        static {
          DEFAULT_INSTANCE = new pb.example4.SearchResponseProto.SearchResponse.Result.Order();
        }

        public static pb.example4.SearchResponseProto.SearchResponse.Result.Order getDefaultInstance() {
          return DEFAULT_INSTANCE;
        }

        @java.lang.Deprecated public static final com.google.protobuf.Parser<Order>
            PARSER = new com.google.protobuf.AbstractParser<Order>() {
          @java.lang.Override
          public Order parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
            return new Order(input, extensionRegistry);
          }
        };

        public static com.google.protobuf.Parser<Order> parser() {
          return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Order> getParserForType() {
          return PARSER;
        }

        @java.lang.Override
        public pb.example4.SearchResponseProto.SearchResponse.Result.Order getDefaultInstanceForType() {
          return DEFAULT_INSTANCE;
        }

      }

      private int bitField0_;
      public static final int COUNT_FIELD_NUMBER = 1;
      private int count_;
      /**
       * <code>required int32 count = 1;</code>
       */
      public boolean hasCount() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 count = 1;</code>
       */
      public int getCount() {
        return count_;
      }

      public static final int ORDERS_FIELD_NUMBER = 2;
      private java.util.List<pb.example4.SearchResponseProto.SearchResponse.Result.Order> orders_;
      /**
       * <code>repeated .pb.example4.SearchResponse.Result.Order orders = 2;</code>
       */
      public java.util.List<pb.example4.SearchResponseProto.SearchResponse.Result.Order> getOrdersList() {
        return orders_;
      }
      /**
       * <code>repeated .pb.example4.SearchResponse.Result.Order orders = 2;</code>
       */
      public java.util.List<? extends pb.example4.SearchResponseProto.SearchResponse.Result.OrderOrBuilder> 
          getOrdersOrBuilderList() {
        return orders_;
      }
      /**
       * <code>repeated .pb.example4.SearchResponse.Result.Order orders = 2;</code>
       */
      public int getOrdersCount() {
        return orders_.size();
      }
      /**
       * <code>repeated .pb.example4.SearchResponse.Result.Order orders = 2;</code>
       */
      public pb.example4.SearchResponseProto.SearchResponse.Result.Order getOrders(int index) {
        return orders_.get(index);
      }
      /**
       * <code>repeated .pb.example4.SearchResponse.Result.Order orders = 2;</code>
       */
      public pb.example4.SearchResponseProto.SearchResponse.Result.OrderOrBuilder getOrdersOrBuilder(
          int index) {
        return orders_.get(index);
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasCount()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, count_);
        }
        for (int i = 0; i < orders_.size(); i++) {
          output.writeMessage(2, orders_.get(i));
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, count_);
        }
        for (int i = 0; i < orders_.size(); i++) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, orders_.get(i));
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof pb.example4.SearchResponseProto.SearchResponse.Result)) {
          return super.equals(obj);
        }
        pb.example4.SearchResponseProto.SearchResponse.Result other = (pb.example4.SearchResponseProto.SearchResponse.Result) obj;

        boolean result = true;
        result = result && (hasCount() == other.hasCount());
        if (hasCount()) {
          result = result && (getCount()
              == other.getCount());
        }
        result = result && getOrdersList()
            .equals(other.getOrdersList());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasCount()) {
          hash = (37 * hash) + COUNT_FIELD_NUMBER;
          hash = (53 * hash) + getCount();
        }
        if (getOrdersCount() > 0) {
          hash = (37 * hash) + ORDERS_FIELD_NUMBER;
          hash = (53 * hash) + getOrdersList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static pb.example4.SearchResponseProto.SearchResponse.Result parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static pb.example4.SearchResponseProto.SearchResponse.Result parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static pb.example4.SearchResponseProto.SearchResponse.Result parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static pb.example4.SearchResponseProto.SearchResponse.Result parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static pb.example4.SearchResponseProto.SearchResponse.Result parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static pb.example4.SearchResponseProto.SearchResponse.Result parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static pb.example4.SearchResponseProto.SearchResponse.Result parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static pb.example4.SearchResponseProto.SearchResponse.Result parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static pb.example4.SearchResponseProto.SearchResponse.Result parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static pb.example4.SearchResponseProto.SearchResponse.Result parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static pb.example4.SearchResponseProto.SearchResponse.Result parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static pb.example4.SearchResponseProto.SearchResponse.Result parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(pb.example4.SearchResponseProto.SearchResponse.Result prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code pb.example4.SearchResponse.Result}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:pb.example4.SearchResponse.Result)
          pb.example4.SearchResponseProto.SearchResponse.ResultOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return pb.example4.SearchResponseProto.internal_static_pb_example4_SearchResponse_Result_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return pb.example4.SearchResponseProto.internal_static_pb_example4_SearchResponse_Result_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  pb.example4.SearchResponseProto.SearchResponse.Result.class, pb.example4.SearchResponseProto.SearchResponse.Result.Builder.class);
        }

        // Construct using pb.example4.SearchResponseProto.SearchResponse.Result.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
            getOrdersFieldBuilder();
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          count_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          if (ordersBuilder_ == null) {
            orders_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ordersBuilder_.clear();
          }
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return pb.example4.SearchResponseProto.internal_static_pb_example4_SearchResponse_Result_descriptor;
        }

        @java.lang.Override
        public pb.example4.SearchResponseProto.SearchResponse.Result getDefaultInstanceForType() {
          return pb.example4.SearchResponseProto.SearchResponse.Result.getDefaultInstance();
        }

        @java.lang.Override
        public pb.example4.SearchResponseProto.SearchResponse.Result build() {
          pb.example4.SearchResponseProto.SearchResponse.Result result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public pb.example4.SearchResponseProto.SearchResponse.Result buildPartial() {
          pb.example4.SearchResponseProto.SearchResponse.Result result = new pb.example4.SearchResponseProto.SearchResponse.Result(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.count_ = count_;
          if (ordersBuilder_ == null) {
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
              orders_ = java.util.Collections.unmodifiableList(orders_);
              bitField0_ = (bitField0_ & ~0x00000002);
            }
            result.orders_ = orders_;
          } else {
            result.orders_ = ordersBuilder_.build();
          }
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return (Builder) super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof pb.example4.SearchResponseProto.SearchResponse.Result) {
            return mergeFrom((pb.example4.SearchResponseProto.SearchResponse.Result)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(pb.example4.SearchResponseProto.SearchResponse.Result other) {
          if (other == pb.example4.SearchResponseProto.SearchResponse.Result.getDefaultInstance()) return this;
          if (other.hasCount()) {
            setCount(other.getCount());
          }
          if (ordersBuilder_ == null) {
            if (!other.orders_.isEmpty()) {
              if (orders_.isEmpty()) {
                orders_ = other.orders_;
                bitField0_ = (bitField0_ & ~0x00000002);
              } else {
                ensureOrdersIsMutable();
                orders_.addAll(other.orders_);
              }
              onChanged();
            }
          } else {
            if (!other.orders_.isEmpty()) {
              if (ordersBuilder_.isEmpty()) {
                ordersBuilder_.dispose();
                ordersBuilder_ = null;
                orders_ = other.orders_;
                bitField0_ = (bitField0_ & ~0x00000002);
                ordersBuilder_ = 
                  com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                     getOrdersFieldBuilder() : null;
              } else {
                ordersBuilder_.addAllMessages(other.orders_);
              }
            }
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          if (!hasCount()) {
            return false;
          }
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          pb.example4.SearchResponseProto.SearchResponse.Result parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (pb.example4.SearchResponseProto.SearchResponse.Result) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int count_ ;
        /**
         * <code>required int32 count = 1;</code>
         */
        public boolean hasCount() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int32 count = 1;</code>
         */
        public int getCount() {
          return count_;
        }
        /**
         * <code>required int32 count = 1;</code>
         */
        public Builder setCount(int value) {
          bitField0_ |= 0x00000001;
          count_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 count = 1;</code>
         */
        public Builder clearCount() {
          bitField0_ = (bitField0_ & ~0x00000001);
          count_ = 0;
          onChanged();
          return this;
        }

        private java.util.List<pb.example4.SearchResponseProto.SearchResponse.Result.Order> orders_ =
          java.util.Collections.emptyList();
        private void ensureOrdersIsMutable() {
          if (!((bitField0_ & 0x00000002) == 0x00000002)) {
            orders_ = new java.util.ArrayList<pb.example4.SearchResponseProto.SearchResponse.Result.Order>(orders_);
            bitField0_ |= 0x00000002;
           }
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
            pb.example4.SearchResponseProto.SearchResponse.Result.Order, pb.example4.SearchResponseProto.SearchResponse.Result.Order.Builder, pb.example4.SearchResponseProto.SearchResponse.Result.OrderOrBuilder> ordersBuilder_;

        /**
         * <code>repeated .pb.example4.SearchResponse.Result.Order orders = 2;</code>
         */
        public java.util.List<pb.example4.SearchResponseProto.SearchResponse.Result.Order> getOrdersList() {
          if (ordersBuilder_ == null) {
            return java.util.Collections.unmodifiableList(orders_);
          } else {
            return ordersBuilder_.getMessageList();
          }
        }
        /**
         * <code>repeated .pb.example4.SearchResponse.Result.Order orders = 2;</code>
         */
        public int getOrdersCount() {
          if (ordersBuilder_ == null) {
            return orders_.size();
          } else {
            return ordersBuilder_.getCount();
          }
        }
        /**
         * <code>repeated .pb.example4.SearchResponse.Result.Order orders = 2;</code>
         */
        public pb.example4.SearchResponseProto.SearchResponse.Result.Order getOrders(int index) {
          if (ordersBuilder_ == null) {
            return orders_.get(index);
          } else {
            return ordersBuilder_.getMessage(index);
          }
        }
        /**
         * <code>repeated .pb.example4.SearchResponse.Result.Order orders = 2;</code>
         */
        public Builder setOrders(
            int index, pb.example4.SearchResponseProto.SearchResponse.Result.Order value) {
          if (ordersBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureOrdersIsMutable();
            orders_.set(index, value);
            onChanged();
          } else {
            ordersBuilder_.setMessage(index, value);
          }
          return this;
        }
        /**
         * <code>repeated .pb.example4.SearchResponse.Result.Order orders = 2;</code>
         */
        public Builder setOrders(
            int index, pb.example4.SearchResponseProto.SearchResponse.Result.Order.Builder builderForValue) {
          if (ordersBuilder_ == null) {
            ensureOrdersIsMutable();
            orders_.set(index, builderForValue.build());
            onChanged();
          } else {
            ordersBuilder_.setMessage(index, builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .pb.example4.SearchResponse.Result.Order orders = 2;</code>
         */
        public Builder addOrders(pb.example4.SearchResponseProto.SearchResponse.Result.Order value) {
          if (ordersBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureOrdersIsMutable();
            orders_.add(value);
            onChanged();
          } else {
            ordersBuilder_.addMessage(value);
          }
          return this;
        }
        /**
         * <code>repeated .pb.example4.SearchResponse.Result.Order orders = 2;</code>
         */
        public Builder addOrders(
            int index, pb.example4.SearchResponseProto.SearchResponse.Result.Order value) {
          if (ordersBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureOrdersIsMutable();
            orders_.add(index, value);
            onChanged();
          } else {
            ordersBuilder_.addMessage(index, value);
          }
          return this;
        }
        /**
         * <code>repeated .pb.example4.SearchResponse.Result.Order orders = 2;</code>
         */
        public Builder addOrders(
            pb.example4.SearchResponseProto.SearchResponse.Result.Order.Builder builderForValue) {
          if (ordersBuilder_ == null) {
            ensureOrdersIsMutable();
            orders_.add(builderForValue.build());
            onChanged();
          } else {
            ordersBuilder_.addMessage(builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .pb.example4.SearchResponse.Result.Order orders = 2;</code>
         */
        public Builder addOrders(
            int index, pb.example4.SearchResponseProto.SearchResponse.Result.Order.Builder builderForValue) {
          if (ordersBuilder_ == null) {
            ensureOrdersIsMutable();
            orders_.add(index, builderForValue.build());
            onChanged();
          } else {
            ordersBuilder_.addMessage(index, builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .pb.example4.SearchResponse.Result.Order orders = 2;</code>
         */
        public Builder addAllOrders(
            java.lang.Iterable<? extends pb.example4.SearchResponseProto.SearchResponse.Result.Order> values) {
          if (ordersBuilder_ == null) {
            ensureOrdersIsMutable();
            com.google.protobuf.AbstractMessageLite.Builder.addAll(
                values, orders_);
            onChanged();
          } else {
            ordersBuilder_.addAllMessages(values);
          }
          return this;
        }
        /**
         * <code>repeated .pb.example4.SearchResponse.Result.Order orders = 2;</code>
         */
        public Builder clearOrders() {
          if (ordersBuilder_ == null) {
            orders_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000002);
            onChanged();
          } else {
            ordersBuilder_.clear();
          }
          return this;
        }
        /**
         * <code>repeated .pb.example4.SearchResponse.Result.Order orders = 2;</code>
         */
        public Builder removeOrders(int index) {
          if (ordersBuilder_ == null) {
            ensureOrdersIsMutable();
            orders_.remove(index);
            onChanged();
          } else {
            ordersBuilder_.remove(index);
          }
          return this;
        }
        /**
         * <code>repeated .pb.example4.SearchResponse.Result.Order orders = 2;</code>
         */
        public pb.example4.SearchResponseProto.SearchResponse.Result.Order.Builder getOrdersBuilder(
            int index) {
          return getOrdersFieldBuilder().getBuilder(index);
        }
        /**
         * <code>repeated .pb.example4.SearchResponse.Result.Order orders = 2;</code>
         */
        public pb.example4.SearchResponseProto.SearchResponse.Result.OrderOrBuilder getOrdersOrBuilder(
            int index) {
          if (ordersBuilder_ == null) {
            return orders_.get(index);  } else {
            return ordersBuilder_.getMessageOrBuilder(index);
          }
        }
        /**
         * <code>repeated .pb.example4.SearchResponse.Result.Order orders = 2;</code>
         */
        public java.util.List<? extends pb.example4.SearchResponseProto.SearchResponse.Result.OrderOrBuilder> 
             getOrdersOrBuilderList() {
          if (ordersBuilder_ != null) {
            return ordersBuilder_.getMessageOrBuilderList();
          } else {
            return java.util.Collections.unmodifiableList(orders_);
          }
        }
        /**
         * <code>repeated .pb.example4.SearchResponse.Result.Order orders = 2;</code>
         */
        public pb.example4.SearchResponseProto.SearchResponse.Result.Order.Builder addOrdersBuilder() {
          return getOrdersFieldBuilder().addBuilder(
              pb.example4.SearchResponseProto.SearchResponse.Result.Order.getDefaultInstance());
        }
        /**
         * <code>repeated .pb.example4.SearchResponse.Result.Order orders = 2;</code>
         */
        public pb.example4.SearchResponseProto.SearchResponse.Result.Order.Builder addOrdersBuilder(
            int index) {
          return getOrdersFieldBuilder().addBuilder(
              index, pb.example4.SearchResponseProto.SearchResponse.Result.Order.getDefaultInstance());
        }
        /**
         * <code>repeated .pb.example4.SearchResponse.Result.Order orders = 2;</code>
         */
        public java.util.List<pb.example4.SearchResponseProto.SearchResponse.Result.Order.Builder> 
             getOrdersBuilderList() {
          return getOrdersFieldBuilder().getBuilderList();
        }
        private com.google.protobuf.RepeatedFieldBuilderV3<
            pb.example4.SearchResponseProto.SearchResponse.Result.Order, pb.example4.SearchResponseProto.SearchResponse.Result.Order.Builder, pb.example4.SearchResponseProto.SearchResponse.Result.OrderOrBuilder> 
            getOrdersFieldBuilder() {
          if (ordersBuilder_ == null) {
            ordersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                pb.example4.SearchResponseProto.SearchResponse.Result.Order, pb.example4.SearchResponseProto.SearchResponse.Result.Order.Builder, pb.example4.SearchResponseProto.SearchResponse.Result.OrderOrBuilder>(
                    orders_,
                    ((bitField0_ & 0x00000002) == 0x00000002),
                    getParentForChildren(),
                    isClean());
            orders_ = null;
          }
          return ordersBuilder_;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:pb.example4.SearchResponse.Result)
      }

      // @@protoc_insertion_point(class_scope:pb.example4.SearchResponse.Result)
      private static final pb.example4.SearchResponseProto.SearchResponse.Result DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new pb.example4.SearchResponseProto.SearchResponse.Result();
      }

      public static pb.example4.SearchResponseProto.SearchResponse.Result getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<Result>
          PARSER = new com.google.protobuf.AbstractParser<Result>() {
        @java.lang.Override
        public Result parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Result(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Result> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Result> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public pb.example4.SearchResponseProto.SearchResponse.Result getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int RESULT_FIELD_NUMBER = 1;
    private pb.example4.SearchResponseProto.SearchResponse.Result result_;
    /**
     * <code>optional .pb.example4.SearchResponse.Result result = 1;</code>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .pb.example4.SearchResponse.Result result = 1;</code>
     */
    public pb.example4.SearchResponseProto.SearchResponse.Result getResult() {
      return result_ == null ? pb.example4.SearchResponseProto.SearchResponse.Result.getDefaultInstance() : result_;
    }
    /**
     * <code>optional .pb.example4.SearchResponse.Result result = 1;</code>
     */
    public pb.example4.SearchResponseProto.SearchResponse.ResultOrBuilder getResultOrBuilder() {
      return result_ == null ? pb.example4.SearchResponseProto.SearchResponse.Result.getDefaultInstance() : result_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasResult()) {
        if (!getResult().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getResult());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getResult());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pb.example4.SearchResponseProto.SearchResponse)) {
        return super.equals(obj);
      }
      pb.example4.SearchResponseProto.SearchResponse other = (pb.example4.SearchResponseProto.SearchResponse) obj;

      boolean result = true;
      result = result && (hasResult() == other.hasResult());
      if (hasResult()) {
        result = result && getResult()
            .equals(other.getResult());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasResult()) {
        hash = (37 * hash) + RESULT_FIELD_NUMBER;
        hash = (53 * hash) + getResult().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pb.example4.SearchResponseProto.SearchResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.example4.SearchResponseProto.SearchResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.example4.SearchResponseProto.SearchResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.example4.SearchResponseProto.SearchResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.example4.SearchResponseProto.SearchResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.example4.SearchResponseProto.SearchResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.example4.SearchResponseProto.SearchResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pb.example4.SearchResponseProto.SearchResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pb.example4.SearchResponseProto.SearchResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pb.example4.SearchResponseProto.SearchResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pb.example4.SearchResponseProto.SearchResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pb.example4.SearchResponseProto.SearchResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pb.example4.SearchResponseProto.SearchResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pb.example4.SearchResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb.example4.SearchResponse)
        pb.example4.SearchResponseProto.SearchResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pb.example4.SearchResponseProto.internal_static_pb_example4_SearchResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pb.example4.SearchResponseProto.internal_static_pb_example4_SearchResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pb.example4.SearchResponseProto.SearchResponse.class, pb.example4.SearchResponseProto.SearchResponse.Builder.class);
      }

      // Construct using pb.example4.SearchResponseProto.SearchResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getResultFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (resultBuilder_ == null) {
          result_ = null;
        } else {
          resultBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pb.example4.SearchResponseProto.internal_static_pb_example4_SearchResponse_descriptor;
      }

      @java.lang.Override
      public pb.example4.SearchResponseProto.SearchResponse getDefaultInstanceForType() {
        return pb.example4.SearchResponseProto.SearchResponse.getDefaultInstance();
      }

      @java.lang.Override
      public pb.example4.SearchResponseProto.SearchResponse build() {
        pb.example4.SearchResponseProto.SearchResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pb.example4.SearchResponseProto.SearchResponse buildPartial() {
        pb.example4.SearchResponseProto.SearchResponse result = new pb.example4.SearchResponseProto.SearchResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (resultBuilder_ == null) {
          result.result_ = result_;
        } else {
          result.result_ = resultBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pb.example4.SearchResponseProto.SearchResponse) {
          return mergeFrom((pb.example4.SearchResponseProto.SearchResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pb.example4.SearchResponseProto.SearchResponse other) {
        if (other == pb.example4.SearchResponseProto.SearchResponse.getDefaultInstance()) return this;
        if (other.hasResult()) {
          mergeResult(other.getResult());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (hasResult()) {
          if (!getResult().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pb.example4.SearchResponseProto.SearchResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pb.example4.SearchResponseProto.SearchResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private pb.example4.SearchResponseProto.SearchResponse.Result result_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          pb.example4.SearchResponseProto.SearchResponse.Result, pb.example4.SearchResponseProto.SearchResponse.Result.Builder, pb.example4.SearchResponseProto.SearchResponse.ResultOrBuilder> resultBuilder_;
      /**
       * <code>optional .pb.example4.SearchResponse.Result result = 1;</code>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .pb.example4.SearchResponse.Result result = 1;</code>
       */
      public pb.example4.SearchResponseProto.SearchResponse.Result getResult() {
        if (resultBuilder_ == null) {
          return result_ == null ? pb.example4.SearchResponseProto.SearchResponse.Result.getDefaultInstance() : result_;
        } else {
          return resultBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .pb.example4.SearchResponse.Result result = 1;</code>
       */
      public Builder setResult(pb.example4.SearchResponseProto.SearchResponse.Result value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          result_ = value;
          onChanged();
        } else {
          resultBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .pb.example4.SearchResponse.Result result = 1;</code>
       */
      public Builder setResult(
          pb.example4.SearchResponseProto.SearchResponse.Result.Builder builderForValue) {
        if (resultBuilder_ == null) {
          result_ = builderForValue.build();
          onChanged();
        } else {
          resultBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .pb.example4.SearchResponse.Result result = 1;</code>
       */
      public Builder mergeResult(pb.example4.SearchResponseProto.SearchResponse.Result value) {
        if (resultBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              result_ != null &&
              result_ != pb.example4.SearchResponseProto.SearchResponse.Result.getDefaultInstance()) {
            result_ =
              pb.example4.SearchResponseProto.SearchResponse.Result.newBuilder(result_).mergeFrom(value).buildPartial();
          } else {
            result_ = value;
          }
          onChanged();
        } else {
          resultBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .pb.example4.SearchResponse.Result result = 1;</code>
       */
      public Builder clearResult() {
        if (resultBuilder_ == null) {
          result_ = null;
          onChanged();
        } else {
          resultBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .pb.example4.SearchResponse.Result result = 1;</code>
       */
      public pb.example4.SearchResponseProto.SearchResponse.Result.Builder getResultBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getResultFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .pb.example4.SearchResponse.Result result = 1;</code>
       */
      public pb.example4.SearchResponseProto.SearchResponse.ResultOrBuilder getResultOrBuilder() {
        if (resultBuilder_ != null) {
          return resultBuilder_.getMessageOrBuilder();
        } else {
          return result_ == null ?
              pb.example4.SearchResponseProto.SearchResponse.Result.getDefaultInstance() : result_;
        }
      }
      /**
       * <code>optional .pb.example4.SearchResponse.Result result = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          pb.example4.SearchResponseProto.SearchResponse.Result, pb.example4.SearchResponseProto.SearchResponse.Result.Builder, pb.example4.SearchResponseProto.SearchResponse.ResultOrBuilder> 
          getResultFieldBuilder() {
        if (resultBuilder_ == null) {
          resultBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              pb.example4.SearchResponseProto.SearchResponse.Result, pb.example4.SearchResponseProto.SearchResponse.Result.Builder, pb.example4.SearchResponseProto.SearchResponse.ResultOrBuilder>(
                  getResult(),
                  getParentForChildren(),
                  isClean());
          result_ = null;
        }
        return resultBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pb.example4.SearchResponse)
    }

    // @@protoc_insertion_point(class_scope:pb.example4.SearchResponse)
    private static final pb.example4.SearchResponseProto.SearchResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pb.example4.SearchResponseProto.SearchResponse();
    }

    public static pb.example4.SearchResponseProto.SearchResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SearchResponse>
        PARSER = new com.google.protobuf.AbstractParser<SearchResponse>() {
      @java.lang.Override
      public SearchResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SearchResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SearchResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SearchResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pb.example4.SearchResponseProto.SearchResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_example4_SearchResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_example4_SearchResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_example4_SearchResponse_Result_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_example4_SearchResponse_Result_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_example4_SearchResponse_Result_Order_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_example4_SearchResponse_Result_Order_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035pb/proto/SearchResponse.proto\022\013pb.exam" +
      "ple4\"\304\001\n\016SearchResponse\0222\n\006result\030\001 \001(\0132" +
      "\".pb.example4.SearchResponse.Result\032~\n\006R" +
      "esult\022\r\n\005count\030\001 \002(\005\0228\n\006orders\030\002 \003(\0132(.p" +
      "b.example4.SearchResponse.Result.Order\032+" +
      "\n\005Order\022\021\n\torder_num\030\001 \001(\t\022\017\n\007address\030\002 " +
      "\001(\tB\"\n\013pb.example4B\023SearchResponseProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_pb_example4_SearchResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pb_example4_SearchResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_example4_SearchResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_pb_example4_SearchResponse_Result_descriptor =
      internal_static_pb_example4_SearchResponse_descriptor.getNestedTypes().get(0);
    internal_static_pb_example4_SearchResponse_Result_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_example4_SearchResponse_Result_descriptor,
        new java.lang.String[] { "Count", "Orders", });
    internal_static_pb_example4_SearchResponse_Result_Order_descriptor =
      internal_static_pb_example4_SearchResponse_Result_descriptor.getNestedTypes().get(0);
    internal_static_pb_example4_SearchResponse_Result_Order_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_example4_SearchResponse_Result_Order_descriptor,
        new java.lang.String[] { "OrderNum", "Address", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
