// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb/proto/UpdatePerson.proto

package pb.example2;

public final class UpdatePerson {
  private UpdatePerson() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb.example2.Person)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    /**
     * <pre>
     *    optional string name = 2;
     * </pre>
     *
     * <code>repeated string phones = 3;</code>
     */
    java.util.List<java.lang.String>
        getPhonesList();
    /**
     * <pre>
     *    optional string name = 2;
     * </pre>
     *
     * <code>repeated string phones = 3;</code>
     */
    int getPhonesCount();
    /**
     * <pre>
     *    optional string name = 2;
     * </pre>
     *
     * <code>repeated string phones = 3;</code>
     */
    java.lang.String getPhones(int index);
    /**
     * <pre>
     *    optional string name = 2;
     * </pre>
     *
     * <code>repeated string phones = 3;</code>
     */
    com.google.protobuf.ByteString
        getPhonesBytes(int index);

    /**
     * <code>optional string login = 4;</code>
     */
    boolean hasLogin();
    /**
     * <code>optional string login = 4;</code>
     */
    java.lang.String getLogin();
    /**
     * <code>optional string login = 4;</code>
     */
    com.google.protobuf.ByteString
        getLoginBytes();
  }
  /**
   * Protobuf type {@code pb.example2.Person}
   */
  public  static final class Person extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pb.example2.Person)
      PersonOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Person() {
      id_ = 0;
      phones_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      login_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                phones_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              phones_.add(bs);
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              login_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          phones_ = phones_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pb.example2.UpdatePerson.internal_static_pb_example2_Person_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pb.example2.UpdatePerson.internal_static_pb_example2_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pb.example2.UpdatePerson.Person.class, pb.example2.UpdatePerson.Person.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int PHONES_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList phones_;
    /**
     * <pre>
     *    optional string name = 2;
     * </pre>
     *
     * <code>repeated string phones = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getPhonesList() {
      return phones_;
    }
    /**
     * <pre>
     *    optional string name = 2;
     * </pre>
     *
     * <code>repeated string phones = 3;</code>
     */
    public int getPhonesCount() {
      return phones_.size();
    }
    /**
     * <pre>
     *    optional string name = 2;
     * </pre>
     *
     * <code>repeated string phones = 3;</code>
     */
    public java.lang.String getPhones(int index) {
      return phones_.get(index);
    }
    /**
     * <pre>
     *    optional string name = 2;
     * </pre>
     *
     * <code>repeated string phones = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPhonesBytes(int index) {
      return phones_.getByteString(index);
    }

    public static final int LOGIN_FIELD_NUMBER = 4;
    private volatile java.lang.Object login_;
    /**
     * <code>optional string login = 4;</code>
     */
    public boolean hasLogin() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string login = 4;</code>
     */
    public java.lang.String getLogin() {
      java.lang.Object ref = login_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          login_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string login = 4;</code>
     */
    public com.google.protobuf.ByteString
        getLoginBytes() {
      java.lang.Object ref = login_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        login_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      for (int i = 0; i < phones_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, phones_.getRaw(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, login_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < phones_.size(); i++) {
          dataSize += computeStringSizeNoTag(phones_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getPhonesList().size();
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, login_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pb.example2.UpdatePerson.Person)) {
        return super.equals(obj);
      }
      pb.example2.UpdatePerson.Person other = (pb.example2.UpdatePerson.Person) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && (getId()
            == other.getId());
      }
      result = result && getPhonesList()
          .equals(other.getPhonesList());
      result = result && (hasLogin() == other.hasLogin());
      if (hasLogin()) {
        result = result && getLogin()
            .equals(other.getLogin());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
      }
      if (getPhonesCount() > 0) {
        hash = (37 * hash) + PHONES_FIELD_NUMBER;
        hash = (53 * hash) + getPhonesList().hashCode();
      }
      if (hasLogin()) {
        hash = (37 * hash) + LOGIN_FIELD_NUMBER;
        hash = (53 * hash) + getLogin().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pb.example2.UpdatePerson.Person parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.example2.UpdatePerson.Person parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.example2.UpdatePerson.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.example2.UpdatePerson.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.example2.UpdatePerson.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.example2.UpdatePerson.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.example2.UpdatePerson.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pb.example2.UpdatePerson.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pb.example2.UpdatePerson.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pb.example2.UpdatePerson.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pb.example2.UpdatePerson.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pb.example2.UpdatePerson.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pb.example2.UpdatePerson.Person prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pb.example2.Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb.example2.Person)
        pb.example2.UpdatePerson.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pb.example2.UpdatePerson.internal_static_pb_example2_Person_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pb.example2.UpdatePerson.internal_static_pb_example2_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pb.example2.UpdatePerson.Person.class, pb.example2.UpdatePerson.Person.Builder.class);
      }

      // Construct using pb.example2.UpdatePerson.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        phones_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        login_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pb.example2.UpdatePerson.internal_static_pb_example2_Person_descriptor;
      }

      @java.lang.Override
      public pb.example2.UpdatePerson.Person getDefaultInstanceForType() {
        return pb.example2.UpdatePerson.Person.getDefaultInstance();
      }

      @java.lang.Override
      public pb.example2.UpdatePerson.Person build() {
        pb.example2.UpdatePerson.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pb.example2.UpdatePerson.Person buildPartial() {
        pb.example2.UpdatePerson.Person result = new pb.example2.UpdatePerson.Person(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          phones_ = phones_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.phones_ = phones_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.login_ = login_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pb.example2.UpdatePerson.Person) {
          return mergeFrom((pb.example2.UpdatePerson.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pb.example2.UpdatePerson.Person other) {
        if (other == pb.example2.UpdatePerson.Person.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (!other.phones_.isEmpty()) {
          if (phones_.isEmpty()) {
            phones_ = other.phones_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensurePhonesIsMutable();
            phones_.addAll(other.phones_);
          }
          onChanged();
        }
        if (other.hasLogin()) {
          bitField0_ |= 0x00000004;
          login_ = other.login_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pb.example2.UpdatePerson.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pb.example2.UpdatePerson.Person) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList phones_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensurePhonesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          phones_ = new com.google.protobuf.LazyStringArrayList(phones_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <pre>
       *    optional string name = 2;
       * </pre>
       *
       * <code>repeated string phones = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getPhonesList() {
        return phones_.getUnmodifiableView();
      }
      /**
       * <pre>
       *    optional string name = 2;
       * </pre>
       *
       * <code>repeated string phones = 3;</code>
       */
      public int getPhonesCount() {
        return phones_.size();
      }
      /**
       * <pre>
       *    optional string name = 2;
       * </pre>
       *
       * <code>repeated string phones = 3;</code>
       */
      public java.lang.String getPhones(int index) {
        return phones_.get(index);
      }
      /**
       * <pre>
       *    optional string name = 2;
       * </pre>
       *
       * <code>repeated string phones = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPhonesBytes(int index) {
        return phones_.getByteString(index);
      }
      /**
       * <pre>
       *    optional string name = 2;
       * </pre>
       *
       * <code>repeated string phones = 3;</code>
       */
      public Builder setPhones(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePhonesIsMutable();
        phones_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *    optional string name = 2;
       * </pre>
       *
       * <code>repeated string phones = 3;</code>
       */
      public Builder addPhones(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePhonesIsMutable();
        phones_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *    optional string name = 2;
       * </pre>
       *
       * <code>repeated string phones = 3;</code>
       */
      public Builder addAllPhones(
          java.lang.Iterable<java.lang.String> values) {
        ensurePhonesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, phones_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *    optional string name = 2;
       * </pre>
       *
       * <code>repeated string phones = 3;</code>
       */
      public Builder clearPhones() {
        phones_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *    optional string name = 2;
       * </pre>
       *
       * <code>repeated string phones = 3;</code>
       */
      public Builder addPhonesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensurePhonesIsMutable();
        phones_.add(value);
        onChanged();
        return this;
      }

      private java.lang.Object login_ = "";
      /**
       * <code>optional string login = 4;</code>
       */
      public boolean hasLogin() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string login = 4;</code>
       */
      public java.lang.String getLogin() {
        java.lang.Object ref = login_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            login_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string login = 4;</code>
       */
      public com.google.protobuf.ByteString
          getLoginBytes() {
        java.lang.Object ref = login_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          login_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string login = 4;</code>
       */
      public Builder setLogin(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        login_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string login = 4;</code>
       */
      public Builder clearLogin() {
        bitField0_ = (bitField0_ & ~0x00000004);
        login_ = getDefaultInstance().getLogin();
        onChanged();
        return this;
      }
      /**
       * <code>optional string login = 4;</code>
       */
      public Builder setLoginBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        login_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pb.example2.Person)
    }

    // @@protoc_insertion_point(class_scope:pb.example2.Person)
    private static final pb.example2.UpdatePerson.Person DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pb.example2.UpdatePerson.Person();
    }

    public static pb.example2.UpdatePerson.Person getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Person>
        PARSER = new com.google.protobuf.AbstractParser<Person>() {
      @java.lang.Override
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Person(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Person> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pb.example2.UpdatePerson.Person getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_example2_Person_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_example2_Person_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033pb/proto/UpdatePerson.proto\022\013pb.exampl" +
      "e2\"9\n\006Person\022\n\n\002id\030\001 \002(\005\022\016\n\006phones\030\003 \003(\t" +
      "\022\r\n\005login\030\004 \001(\tJ\004\010\002\020\003B\033\n\013pb.example2B\014Up" +
      "datePerson"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_pb_example2_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pb_example2_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_example2_Person_descriptor,
        new java.lang.String[] { "Id", "Phones", "Login", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
