// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb/proto/Student.proto

package pb.example3;

public final class StudentProto {
  private StudentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StudentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb.example3.Student)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional .pb.example3.Teacher teacher = 2;</code>
     */
    boolean hasTeacher();
    /**
     * <code>optional .pb.example3.Teacher teacher = 2;</code>
     */
    pb.example3.TeacherProto.Teacher getTeacher();
    /**
     * <code>optional .pb.example3.Teacher teacher = 2;</code>
     */
    pb.example3.TeacherProto.TeacherOrBuilder getTeacherOrBuilder();

    /**
     * <code>optional .pb.example3.Address homeAddress = 3;</code>
     */
    boolean hasHomeAddress();
    /**
     * <code>optional .pb.example3.Address homeAddress = 3;</code>
     */
    pb.example3.AddressProto.Address getHomeAddress();
    /**
     * <code>optional .pb.example3.Address homeAddress = 3;</code>
     */
    pb.example3.AddressProto.AddressOrBuilder getHomeAddressOrBuilder();
  }
  /**
   * Protobuf type {@code pb.example3.Student}
   */
  public  static final class Student extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pb.example3.Student)
      StudentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Student.newBuilder() to construct.
    private Student(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Student() {
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Student(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 18: {
              pb.example3.TeacherProto.Teacher.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = teacher_.toBuilder();
              }
              teacher_ = input.readMessage(pb.example3.TeacherProto.Teacher.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(teacher_);
                teacher_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              pb.example3.AddressProto.Address.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = homeAddress_.toBuilder();
              }
              homeAddress_ = input.readMessage(pb.example3.AddressProto.Address.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(homeAddress_);
                homeAddress_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pb.example3.StudentProto.internal_static_pb_example3_Student_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pb.example3.StudentProto.internal_static_pb_example3_Student_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pb.example3.StudentProto.Student.class, pb.example3.StudentProto.Student.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TEACHER_FIELD_NUMBER = 2;
    private pb.example3.TeacherProto.Teacher teacher_;
    /**
     * <code>optional .pb.example3.Teacher teacher = 2;</code>
     */
    public boolean hasTeacher() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .pb.example3.Teacher teacher = 2;</code>
     */
    public pb.example3.TeacherProto.Teacher getTeacher() {
      return teacher_ == null ? pb.example3.TeacherProto.Teacher.getDefaultInstance() : teacher_;
    }
    /**
     * <code>optional .pb.example3.Teacher teacher = 2;</code>
     */
    public pb.example3.TeacherProto.TeacherOrBuilder getTeacherOrBuilder() {
      return teacher_ == null ? pb.example3.TeacherProto.Teacher.getDefaultInstance() : teacher_;
    }

    public static final int HOMEADDRESS_FIELD_NUMBER = 3;
    private pb.example3.AddressProto.Address homeAddress_;
    /**
     * <code>optional .pb.example3.Address homeAddress = 3;</code>
     */
    public boolean hasHomeAddress() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .pb.example3.Address homeAddress = 3;</code>
     */
    public pb.example3.AddressProto.Address getHomeAddress() {
      return homeAddress_ == null ? pb.example3.AddressProto.Address.getDefaultInstance() : homeAddress_;
    }
    /**
     * <code>optional .pb.example3.Address homeAddress = 3;</code>
     */
    public pb.example3.AddressProto.AddressOrBuilder getHomeAddressOrBuilder() {
      return homeAddress_ == null ? pb.example3.AddressProto.Address.getDefaultInstance() : homeAddress_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, getTeacher());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, getHomeAddress());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getTeacher());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getHomeAddress());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pb.example3.StudentProto.Student)) {
        return super.equals(obj);
      }
      pb.example3.StudentProto.Student other = (pb.example3.StudentProto.Student) obj;

      boolean result = true;
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && (hasTeacher() == other.hasTeacher());
      if (hasTeacher()) {
        result = result && getTeacher()
            .equals(other.getTeacher());
      }
      result = result && (hasHomeAddress() == other.hasHomeAddress());
      if (hasHomeAddress()) {
        result = result && getHomeAddress()
            .equals(other.getHomeAddress());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasTeacher()) {
        hash = (37 * hash) + TEACHER_FIELD_NUMBER;
        hash = (53 * hash) + getTeacher().hashCode();
      }
      if (hasHomeAddress()) {
        hash = (37 * hash) + HOMEADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getHomeAddress().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pb.example3.StudentProto.Student parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.example3.StudentProto.Student parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.example3.StudentProto.Student parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.example3.StudentProto.Student parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.example3.StudentProto.Student parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.example3.StudentProto.Student parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.example3.StudentProto.Student parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pb.example3.StudentProto.Student parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pb.example3.StudentProto.Student parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pb.example3.StudentProto.Student parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pb.example3.StudentProto.Student parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pb.example3.StudentProto.Student parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pb.example3.StudentProto.Student prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pb.example3.Student}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb.example3.Student)
        pb.example3.StudentProto.StudentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pb.example3.StudentProto.internal_static_pb_example3_Student_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pb.example3.StudentProto.internal_static_pb_example3_Student_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pb.example3.StudentProto.Student.class, pb.example3.StudentProto.Student.Builder.class);
      }

      // Construct using pb.example3.StudentProto.Student.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTeacherFieldBuilder();
          getHomeAddressFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (teacherBuilder_ == null) {
          teacher_ = null;
        } else {
          teacherBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (homeAddressBuilder_ == null) {
          homeAddress_ = null;
        } else {
          homeAddressBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pb.example3.StudentProto.internal_static_pb_example3_Student_descriptor;
      }

      @java.lang.Override
      public pb.example3.StudentProto.Student getDefaultInstanceForType() {
        return pb.example3.StudentProto.Student.getDefaultInstance();
      }

      @java.lang.Override
      public pb.example3.StudentProto.Student build() {
        pb.example3.StudentProto.Student result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pb.example3.StudentProto.Student buildPartial() {
        pb.example3.StudentProto.Student result = new pb.example3.StudentProto.Student(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (teacherBuilder_ == null) {
          result.teacher_ = teacher_;
        } else {
          result.teacher_ = teacherBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (homeAddressBuilder_ == null) {
          result.homeAddress_ = homeAddress_;
        } else {
          result.homeAddress_ = homeAddressBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pb.example3.StudentProto.Student) {
          return mergeFrom((pb.example3.StudentProto.Student)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pb.example3.StudentProto.Student other) {
        if (other == pb.example3.StudentProto.Student.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasTeacher()) {
          mergeTeacher(other.getTeacher());
        }
        if (other.hasHomeAddress()) {
          mergeHomeAddress(other.getHomeAddress());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pb.example3.StudentProto.Student parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pb.example3.StudentProto.Student) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private pb.example3.TeacherProto.Teacher teacher_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          pb.example3.TeacherProto.Teacher, pb.example3.TeacherProto.Teacher.Builder, pb.example3.TeacherProto.TeacherOrBuilder> teacherBuilder_;
      /**
       * <code>optional .pb.example3.Teacher teacher = 2;</code>
       */
      public boolean hasTeacher() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .pb.example3.Teacher teacher = 2;</code>
       */
      public pb.example3.TeacherProto.Teacher getTeacher() {
        if (teacherBuilder_ == null) {
          return teacher_ == null ? pb.example3.TeacherProto.Teacher.getDefaultInstance() : teacher_;
        } else {
          return teacherBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .pb.example3.Teacher teacher = 2;</code>
       */
      public Builder setTeacher(pb.example3.TeacherProto.Teacher value) {
        if (teacherBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          teacher_ = value;
          onChanged();
        } else {
          teacherBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .pb.example3.Teacher teacher = 2;</code>
       */
      public Builder setTeacher(
          pb.example3.TeacherProto.Teacher.Builder builderForValue) {
        if (teacherBuilder_ == null) {
          teacher_ = builderForValue.build();
          onChanged();
        } else {
          teacherBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .pb.example3.Teacher teacher = 2;</code>
       */
      public Builder mergeTeacher(pb.example3.TeacherProto.Teacher value) {
        if (teacherBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              teacher_ != null &&
              teacher_ != pb.example3.TeacherProto.Teacher.getDefaultInstance()) {
            teacher_ =
              pb.example3.TeacherProto.Teacher.newBuilder(teacher_).mergeFrom(value).buildPartial();
          } else {
            teacher_ = value;
          }
          onChanged();
        } else {
          teacherBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .pb.example3.Teacher teacher = 2;</code>
       */
      public Builder clearTeacher() {
        if (teacherBuilder_ == null) {
          teacher_ = null;
          onChanged();
        } else {
          teacherBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .pb.example3.Teacher teacher = 2;</code>
       */
      public pb.example3.TeacherProto.Teacher.Builder getTeacherBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getTeacherFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .pb.example3.Teacher teacher = 2;</code>
       */
      public pb.example3.TeacherProto.TeacherOrBuilder getTeacherOrBuilder() {
        if (teacherBuilder_ != null) {
          return teacherBuilder_.getMessageOrBuilder();
        } else {
          return teacher_ == null ?
              pb.example3.TeacherProto.Teacher.getDefaultInstance() : teacher_;
        }
      }
      /**
       * <code>optional .pb.example3.Teacher teacher = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          pb.example3.TeacherProto.Teacher, pb.example3.TeacherProto.Teacher.Builder, pb.example3.TeacherProto.TeacherOrBuilder> 
          getTeacherFieldBuilder() {
        if (teacherBuilder_ == null) {
          teacherBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              pb.example3.TeacherProto.Teacher, pb.example3.TeacherProto.Teacher.Builder, pb.example3.TeacherProto.TeacherOrBuilder>(
                  getTeacher(),
                  getParentForChildren(),
                  isClean());
          teacher_ = null;
        }
        return teacherBuilder_;
      }

      private pb.example3.AddressProto.Address homeAddress_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          pb.example3.AddressProto.Address, pb.example3.AddressProto.Address.Builder, pb.example3.AddressProto.AddressOrBuilder> homeAddressBuilder_;
      /**
       * <code>optional .pb.example3.Address homeAddress = 3;</code>
       */
      public boolean hasHomeAddress() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .pb.example3.Address homeAddress = 3;</code>
       */
      public pb.example3.AddressProto.Address getHomeAddress() {
        if (homeAddressBuilder_ == null) {
          return homeAddress_ == null ? pb.example3.AddressProto.Address.getDefaultInstance() : homeAddress_;
        } else {
          return homeAddressBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .pb.example3.Address homeAddress = 3;</code>
       */
      public Builder setHomeAddress(pb.example3.AddressProto.Address value) {
        if (homeAddressBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          homeAddress_ = value;
          onChanged();
        } else {
          homeAddressBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .pb.example3.Address homeAddress = 3;</code>
       */
      public Builder setHomeAddress(
          pb.example3.AddressProto.Address.Builder builderForValue) {
        if (homeAddressBuilder_ == null) {
          homeAddress_ = builderForValue.build();
          onChanged();
        } else {
          homeAddressBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .pb.example3.Address homeAddress = 3;</code>
       */
      public Builder mergeHomeAddress(pb.example3.AddressProto.Address value) {
        if (homeAddressBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              homeAddress_ != null &&
              homeAddress_ != pb.example3.AddressProto.Address.getDefaultInstance()) {
            homeAddress_ =
              pb.example3.AddressProto.Address.newBuilder(homeAddress_).mergeFrom(value).buildPartial();
          } else {
            homeAddress_ = value;
          }
          onChanged();
        } else {
          homeAddressBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .pb.example3.Address homeAddress = 3;</code>
       */
      public Builder clearHomeAddress() {
        if (homeAddressBuilder_ == null) {
          homeAddress_ = null;
          onChanged();
        } else {
          homeAddressBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .pb.example3.Address homeAddress = 3;</code>
       */
      public pb.example3.AddressProto.Address.Builder getHomeAddressBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getHomeAddressFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .pb.example3.Address homeAddress = 3;</code>
       */
      public pb.example3.AddressProto.AddressOrBuilder getHomeAddressOrBuilder() {
        if (homeAddressBuilder_ != null) {
          return homeAddressBuilder_.getMessageOrBuilder();
        } else {
          return homeAddress_ == null ?
              pb.example3.AddressProto.Address.getDefaultInstance() : homeAddress_;
        }
      }
      /**
       * <code>optional .pb.example3.Address homeAddress = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          pb.example3.AddressProto.Address, pb.example3.AddressProto.Address.Builder, pb.example3.AddressProto.AddressOrBuilder> 
          getHomeAddressFieldBuilder() {
        if (homeAddressBuilder_ == null) {
          homeAddressBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              pb.example3.AddressProto.Address, pb.example3.AddressProto.Address.Builder, pb.example3.AddressProto.AddressOrBuilder>(
                  getHomeAddress(),
                  getParentForChildren(),
                  isClean());
          homeAddress_ = null;
        }
        return homeAddressBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pb.example3.Student)
    }

    // @@protoc_insertion_point(class_scope:pb.example3.Student)
    private static final pb.example3.StudentProto.Student DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pb.example3.StudentProto.Student();
    }

    public static pb.example3.StudentProto.Student getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Student>
        PARSER = new com.google.protobuf.AbstractParser<Student>() {
      @java.lang.Override
      public Student parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Student(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Student> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Student> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pb.example3.StudentProto.Student getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_example3_Student_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_example3_Student_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026pb/proto/Student.proto\022\013pb.example3\032\026p" +
      "b/proto/Teacher.proto\"i\n\007Student\022\014\n\004name" +
      "\030\001 \001(\t\022%\n\007teacher\030\002 \001(\0132\024.pb.example3.Te" +
      "acher\022)\n\013homeAddress\030\003 \001(\0132\024.pb.example3" +
      ".AddressB\033\n\013pb.example3B\014StudentProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          pb.example3.TeacherProto.getDescriptor(),
        }, assigner);
    internal_static_pb_example3_Student_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pb_example3_Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_example3_Student_descriptor,
        new java.lang.String[] { "Name", "Teacher", "HomeAddress", });
    pb.example3.TeacherProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
